import type { FoodCategory } from '@/types';

interface ScoreEntry {
  score: number;
  category: FoodCategory;
}

// Curated reference table. Names are normalized: lowercase, singular, no brand
// prefix unless the brand is the identity (coca cola, big mac, nutella).
// The vision model's output is matched against this table; on a hit the
// score+category are overridden so the same food always gets the same score.
export const FOOD_SCORE_TABLE: Record<string, ScoreEntry> = {
  // Whole / healthy
  'spinach': { score: 10, category: 'vegetable_fruit' },
  'kale': { score: 10, category: 'vegetable_fruit' },
  'arugula': { score: 10, category: 'vegetable_fruit' },
  'romaine lettuce': { score: 9, category: 'vegetable_fruit' },
  'lettuce': { score: 9, category: 'vegetable_fruit' },
  'broccoli': { score: 10, category: 'vegetable_fruit' },
  'cauliflower': { score: 9, category: 'vegetable_fruit' },
  'brussels sprout': { score: 10, category: 'vegetable_fruit' },
  'cabbage': { score: 9, category: 'vegetable_fruit' },
  'bell pepper': { score: 9, category: 'vegetable_fruit' },
  'tomato': { score: 9, category: 'vegetable_fruit' },
  'cucumber': { score: 8, category: 'vegetable_fruit' },
  'carrot': { score: 9, category: 'vegetable_fruit' },
  'celery': { score: 8, category: 'vegetable_fruit' },
  'zucchini': { score: 9, category: 'vegetable_fruit' },
  'asparagus': { score: 10, category: 'vegetable_fruit' },
  'green bean': { score: 9, category: 'vegetable_fruit' },
  'mushroom': { score: 9, category: 'vegetable_fruit' },
  'garlic': { score: 9, category: 'vegetable_fruit' },
  'ginger': { score: 9, category: 'vegetable_fruit' },
  'cilantro': { score: 9, category: 'vegetable_fruit' },
  'parsley': { score: 9, category: 'vegetable_fruit' },
  'blueberry': { score: 10, category: 'vegetable_fruit' },
  'raspberry': { score: 10, category: 'vegetable_fruit' },
  'strawberry': { score: 9, category: 'vegetable_fruit' },
  'apple': { score: 9, category: 'vegetable_fruit' },
  'banana': { score: 7, category: 'vegetable_fruit' },
  'orange': { score: 9, category: 'vegetable_fruit' },
  'lemon': { score: 9, category: 'vegetable_fruit' },
  'lime': { score: 9, category: 'vegetable_fruit' },
  'grape': { score: 7, category: 'vegetable_fruit' },
  'watermelon': { score: 7, category: 'vegetable_fruit' },
  'cantaloupe': { score: 8, category: 'vegetable_fruit' },
  'peach': { score: 8, category: 'vegetable_fruit' },
  'avocado': { score: 9, category: 'vegetable_fruit' },
  // Lean proteins
  'chicken breast': { score: 9, category: 'lean_protein' },
  'turkey breast': { score: 9, category: 'lean_protein' },
  'salmon': { score: 10, category: 'lean_protein' },
  'cod': { score: 9, category: 'lean_protein' },
  'tuna': { score: 8, category: 'lean_protein' },
  'sardine': { score: 10, category: 'lean_protein' },
  'shrimp': { score: 8, category: 'lean_protein' },
  'tofu': { score: 9, category: 'lean_protein' },
  'tempeh': { score: 9, category: 'lean_protein' },
  'egg': { score: 8, category: 'lean_protein' },
  // Dairy
  'plain greek yogurt': { score: 9, category: 'dairy' },
  'greek yogurt': { score: 9, category: 'dairy' },
  'cottage cheese': { score: 8, category: 'dairy' },
  'skim milk': { score: 7, category: 'dairy' },
  'whole milk': { score: 6, category: 'dairy' },
  'milk': { score: 6, category: 'dairy' },
  'unsweetened almond milk': { score: 7, category: 'dairy' },
  'kefir': { score: 9, category: 'dairy' },
  // Whole grains / legumes
  'hummus': { score: 8, category: 'whole_grain_legume' },
  'cooked lentil': { score: 10, category: 'whole_grain_legume' },
  'lentil': { score: 10, category: 'whole_grain_legume' },
  'cooked black bean': { score: 10, category: 'whole_grain_legume' },
  'black bean': { score: 10, category: 'whole_grain_legume' },
  'cooked chickpea': { score: 10, category: 'whole_grain_legume' },
  'chickpea': { score: 10, category: 'whole_grain_legume' },
  'cooked quinoa': { score: 9, category: 'whole_grain_legume' },
  'quinoa': { score: 9, category: 'whole_grain_legume' },
  'cooked brown rice': { score: 7, category: 'whole_grain_legume' },
  'brown rice': { score: 7, category: 'whole_grain_legume' },
  'edamame': { score: 9, category: 'whole_grain_legume' },
  'corn tortilla': { score: 1, category: 'whole_grain_legume' },
  // Middle / mixed
  'cheddar cheese': { score: -2, category: 'dairy' },
  'mozzarella cheese': { score: -1, category: 'dairy' },
  'feta cheese': { score: -1, category: 'dairy' },
  'parmesan cheese': { score: 1, category: 'dairy' },
  'cream cheese': { score: -3, category: 'dairy' },
  'american cheese': { score: -4, category: 'processed' },
  'butter': { score: -2, category: 'dairy' },
  'sour cream': { score: -2, category: 'dairy' },
  'whipped cream': { score: -3, category: 'dairy' },
  'coffee creamer': { score: -4, category: 'processed' },
  'deli turkey': { score: -3, category: 'processed' },
  'deli ham': { score: -4, category: 'processed' },
  'bacon': { score: -6, category: 'processed' },
  'sausage': { score: -6, category: 'processed' },
  'hot dog': { score: -7, category: 'processed' },
  'salami': { score: -6, category: 'processed' },
  'pepperoni': { score: -6, category: 'processed' },
  'ketchup': { score: -2, category: 'processed' },
  'yellow mustard': { score: 1, category: 'processed' },
  'dijon mustard': { score: 1, category: 'processed' },
  'mustard': { score: 1, category: 'processed' },
  'mayonnaise': { score: -3, category: 'processed' },
  'mayo': { score: -3, category: 'processed' },
  'sriracha': { score: 1, category: 'processed' },
  'hot sauce': { score: 1, category: 'processed' },
  'ranch dressing': { score: -4, category: 'processed' },
  'bbq sauce': { score: -3, category: 'processed' },
  'soy sauce': { score: -2, category: 'processed' },
  'salsa': { score: 2, category: 'vegetable_fruit' },
  'peanut butter': { score: 3, category: 'processed' },
  'almond butter': { score: 4, category: 'processed' },
  'jam': { score: -3, category: 'processed' },
  'jelly': { score: -3, category: 'processed' },
  'nutella': { score: -5, category: 'processed' },
  'honey': { score: -1, category: 'processed' },
  'maple syrup': { score: -2, category: 'processed' },
  'white rice': { score: -1, category: 'processed' },
  'white pasta': { score: -1, category: 'processed' },
  'flour tortilla': { score: -2, category: 'processed' },
  'white bread': { score: -2, category: 'processed' },
  'pickled cucumber': { score: 2, category: 'vegetable_fruit' },
  'kimchi': { score: 5, category: 'vegetable_fruit' },
  'sauerkraut': { score: 4, category: 'vegetable_fruit' },
  'green olive': { score: 2, category: 'vegetable_fruit' },
  'black olive': { score: 2, category: 'vegetable_fruit' },
  'orange juice': { score: -2, category: 'processed' },
  'apple juice': { score: -3, category: 'processed' },
  'oat milk': { score: -1, category: 'processed' },
  'sweetened almond milk': { score: -2, category: 'processed' },
  'guacamole': { score: 3, category: 'vegetable_fruit' },
  // Junk / fast food / sugary
  'coca cola': { score: -8, category: 'fast_food_sugary' },
  'coke': { score: -8, category: 'fast_food_sugary' },
  'pepsi': { score: -8, category: 'fast_food_sugary' },
  'mountain dew': { score: -9, category: 'fast_food_sugary' },
  'red bull': { score: -8, category: 'fast_food_sugary' },
  'monster energy': { score: -9, category: 'fast_food_sugary' },
  'energy drink': { score: -8, category: 'fast_food_sugary' },
  'soda': { score: -7, category: 'fast_food_sugary' },
  'gatorade': { score: -5, category: 'fast_food_sugary' },
  'powerade': { score: -5, category: 'fast_food_sugary' },
  'sports drink': { score: -5, category: 'fast_food_sugary' },
  'sweet tea': { score: -6, category: 'fast_food_sugary' },
  'sweetened lemonade': { score: -6, category: 'fast_food_sugary' },
  'lemonade': { score: -5, category: 'fast_food_sugary' },
  'starbucks frappuccino': { score: -7, category: 'fast_food_sugary' },
  'frappuccino': { score: -7, category: 'fast_food_sugary' },
  'yoo-hoo': { score: -7, category: 'fast_food_sugary' },
  'chocolate milk': { score: -4, category: 'fast_food_sugary' },
  'diet coke': { score: -2, category: 'fast_food_sugary' },
  'coke zero': { score: -2, category: 'fast_food_sugary' },
  'diet pepsi': { score: -2, category: 'fast_food_sugary' },
  'diet soda': { score: -2, category: 'fast_food_sugary' },
  'beer': { score: -4, category: 'processed' },
  'light beer': { score: -3, category: 'processed' },
  'wine': { score: -4, category: 'processed' },
  'hard seltzer': { score: -3, category: 'processed' },
  'cocktail': { score: -6, category: 'processed' },
  'liquor': { score: -5, category: 'processed' },
  'ice cream': { score: -6, category: 'processed' },
  'cheesecake': { score: -7, category: 'processed' },
  'pudding cup': { score: -5, category: 'processed' },
  'chocolate bar': { score: -7, category: 'processed' },
  'candy': { score: -7, category: 'processed' },
  'gushers': { score: -8, category: 'processed' },
  'mcdonalds burger': { score: -7, category: 'fast_food_sugary' },
  'big mac': { score: -9, category: 'fast_food_sugary' },
  'mcdonalds fries': { score: -7, category: 'fast_food_sugary' },
  'french fries': { score: -6, category: 'fast_food_sugary' },
  'fried chicken': { score: -7, category: 'fast_food_sugary' },
  'chicken nuggets': { score: -7, category: 'processed' },
  'pizza slice': { score: -5, category: 'fast_food_sugary' },
  'pizza': { score: -5, category: 'fast_food_sugary' },
  'chinese takeout fried rice': { score: -6, category: 'fast_food_sugary' },
  'fried rice': { score: -5, category: 'fast_food_sugary' },
  'general tso chicken': { score: -8, category: 'fast_food_sugary' },
  'egg roll': { score: -6, category: 'fast_food_sugary' },
  'frozen pizza': { score: -6, category: 'processed' },
  'hot pocket': { score: -7, category: 'processed' },
  'tv dinner': { score: -7, category: 'processed' },
  'mozzarella sticks': { score: -6, category: 'processed' },
  'frozen chicken nuggets': { score: -7, category: 'processed' },
  'frozen corn dog': { score: -7, category: 'processed' },
  'cheese puffs': { score: -7, category: 'processed' },
  'lunchable': { score: -7, category: 'processed' },
  'string cheese': { score: -2, category: 'processed' },
  'trix yogurt': { score: -5, category: 'processed' },
  'go-gurt': { score: -5, category: 'processed' },
  'flavored yogurt': { score: -4, category: 'processed' },
  'toaster strudel': { score: -7, category: 'processed' },
  'sweetened oatmeal cup': { score: -4, category: 'processed' },
  'frozen waffle': { score: -4, category: 'processed' },
  'cinnamon roll': { score: -7, category: 'processed' },
  'frozen burrito': { score: -6, category: 'processed' },
  'frozen taquito': { score: -6, category: 'processed' },
  // Snacks
  'popcorn': { score: 4, category: 'whole_grain_legume' },
  'air popped popcorn': { score: 6, category: 'whole_grain_legume' },
  'microwave popcorn': { score: -3, category: 'processed' },
  'movie theater popcorn': { score: -5, category: 'processed' },
  'kettle corn': { score: -2, category: 'processed' },
  'pretzel': { score: -3, category: 'processed' },
  'chip': { score: -5, category: 'processed' },
  'potato chip': { score: -5, category: 'processed' },
  'tortilla chip': { score: -4, category: 'processed' },
  'doritos': { score: -6, category: 'processed' },
  'cheetos': { score: -7, category: 'processed' },
  'pita chip': { score: -2, category: 'processed' },
  'cracker': { score: -3, category: 'processed' },
  'graham cracker': { score: -3, category: 'processed' },
  'saltine': { score: -3, category: 'processed' },
  'goldfish': { score: -4, category: 'processed' },
  'oreo': { score: -8, category: 'processed' },
  'chocolate chip cookie': { score: -7, category: 'processed' },
  'cookie': { score: -6, category: 'processed' },
  'brownie': { score: -7, category: 'processed' },
  'donut': { score: -7, category: 'processed' },
  'doughnut': { score: -7, category: 'processed' },
  'muffin': { score: -4, category: 'processed' },
  'cupcake': { score: -7, category: 'processed' },
  'cake': { score: -7, category: 'processed' },
  'pop tart': { score: -7, category: 'processed' },
  'rice cake': { score: 0, category: 'processed' },
  'granola bar': { score: -2, category: 'processed' },
  'protein bar': { score: -1, category: 'processed' },
  'kind bar': { score: 2, category: 'processed' },
  'rxbar': { score: 3, category: 'processed' },
  'fruit snack': { score: -6, category: 'processed' },
  'fruit roll up': { score: -7, category: 'processed' },
  'jerky': { score: -2, category: 'processed' },
  'beef jerky': { score: -2, category: 'processed' },
  'trail mix': { score: 3, category: 'processed' },
  // Nuts / seeds
  'almond': { score: 7, category: 'lean_protein' },
  'walnut': { score: 7, category: 'lean_protein' },
  'cashew': { score: 6, category: 'lean_protein' },
  'peanut': { score: 5, category: 'lean_protein' },
  'pistachio': { score: 7, category: 'lean_protein' },
  'pecan': { score: 6, category: 'lean_protein' },
  'macadamia': { score: 5, category: 'lean_protein' },
  'brazil nut': { score: 7, category: 'lean_protein' },
  'hazelnut': { score: 6, category: 'lean_protein' },
  'pumpkin seed': { score: 8, category: 'lean_protein' },
  'sunflower seed': { score: 6, category: 'lean_protein' },
  'chia seed': { score: 9, category: 'whole_grain_legume' },
  'flax seed': { score: 9, category: 'whole_grain_legume' },
  'hemp seed': { score: 8, category: 'whole_grain_legume' },
  // More fruits
  'mango': { score: 7, category: 'vegetable_fruit' },
  'pineapple': { score: 8, category: 'vegetable_fruit' },
  'kiwi': { score: 9, category: 'vegetable_fruit' },
  'pear': { score: 8, category: 'vegetable_fruit' },
  'plum': { score: 8, category: 'vegetable_fruit' },
  'nectarine': { score: 8, category: 'vegetable_fruit' },
  'apricot': { score: 8, category: 'vegetable_fruit' },
  'cherry': { score: 8, category: 'vegetable_fruit' },
  'pomegranate': { score: 10, category: 'vegetable_fruit' },
  'guava': { score: 9, category: 'vegetable_fruit' },
  'papaya': { score: 9, category: 'vegetable_fruit' },
  'dragonfruit': { score: 8, category: 'vegetable_fruit' },
  'persimmon': { score: 7, category: 'vegetable_fruit' },
  'tangerine': { score: 9, category: 'vegetable_fruit' },
  'clementine': { score: 9, category: 'vegetable_fruit' },
  'mandarin orange': { score: 9, category: 'vegetable_fruit' },
  'fresh fig': { score: 7, category: 'vegetable_fruit' },
  'cranberry': { score: 9, category: 'vegetable_fruit' },
  'blackberry': { score: 10, category: 'vegetable_fruit' },
  'raisin': { score: 4, category: 'vegetable_fruit' },
  'date': { score: 5, category: 'vegetable_fruit' },
  'dried fruit': { score: 2, category: 'vegetable_fruit' },
  // More vegetables
  'eggplant': { score: 9, category: 'vegetable_fruit' },
  'okra': { score: 9, category: 'vegetable_fruit' },
  'artichoke': { score: 10, category: 'vegetable_fruit' },
  'bok choy': { score: 10, category: 'vegetable_fruit' },
  'swiss chard': { score: 10, category: 'vegetable_fruit' },
  'collard green': { score: 10, category: 'vegetable_fruit' },
  'watercress': { score: 10, category: 'vegetable_fruit' },
  'radish': { score: 8, category: 'vegetable_fruit' },
  'sweet potato': { score: 9, category: 'vegetable_fruit' },
  'yam': { score: 8, category: 'vegetable_fruit' },
  'potato': { score: 5, category: 'vegetable_fruit' },
  'corn': { score: 5, category: 'vegetable_fruit' },
  'pea': { score: 9, category: 'vegetable_fruit' },
  'snap pea': { score: 9, category: 'vegetable_fruit' },
  'snow pea': { score: 9, category: 'vegetable_fruit' },
  'fennel': { score: 8, category: 'vegetable_fruit' },
  'leek': { score: 8, category: 'vegetable_fruit' },
  'shallot': { score: 8, category: 'vegetable_fruit' },
  'onion': { score: 8, category: 'vegetable_fruit' },
  'red onion': { score: 8, category: 'vegetable_fruit' },
  'scallion': { score: 9, category: 'vegetable_fruit' },
  'chive': { score: 9, category: 'vegetable_fruit' },
  'basil': { score: 9, category: 'vegetable_fruit' },
  'mint': { score: 9, category: 'vegetable_fruit' },
  'thyme': { score: 9, category: 'vegetable_fruit' },
  'rosemary': { score: 9, category: 'vegetable_fruit' },
  'dill': { score: 9, category: 'vegetable_fruit' },
  'baby spinach': { score: 10, category: 'vegetable_fruit' },
  'mixed greens': { score: 9, category: 'vegetable_fruit' },
  'spring mix': { score: 9, category: 'vegetable_fruit' },
  // Grains / starches
  'oat': { score: 7, category: 'whole_grain_legume' },
  'oatmeal': { score: 7, category: 'whole_grain_legume' },
  'steel cut oat': { score: 8, category: 'whole_grain_legume' },
  'rolled oat': { score: 7, category: 'whole_grain_legume' },
  'instant oatmeal': { score: 2, category: 'processed' },
  'granola': { score: -2, category: 'processed' },
  'cereal': { score: -4, category: 'processed' },
  'frosted flakes': { score: -7, category: 'processed' },
  'lucky charms': { score: -7, category: 'processed' },
  'cheerios': { score: 1, category: 'processed' },
  'wheat bread': { score: 3, category: 'whole_grain_legume' },
  'whole wheat bread': { score: 4, category: 'whole_grain_legume' },
  'sourdough bread': { score: 3, category: 'whole_grain_legume' },
  'rye bread': { score: 3, category: 'whole_grain_legume' },
  'pita bread': { score: 1, category: 'whole_grain_legume' },
  'bagel': { score: -2, category: 'processed' },
  'english muffin': { score: -1, category: 'whole_grain_legume' },
  'whole wheat pasta': { score: 4, category: 'whole_grain_legume' },
  'farro': { score: 8, category: 'whole_grain_legume' },
  'barley': { score: 8, category: 'whole_grain_legume' },
  'bulgur': { score: 8, category: 'whole_grain_legume' },
  'couscous': { score: 4, category: 'whole_grain_legume' },
  'mac and cheese': { score: -4, category: 'processed' },
  'ramen': { score: -5, category: 'processed' },
  'instant noodle': { score: -5, category: 'processed' },
  'canned soup': { score: -2, category: 'processed' },
  // More proteins
  'ground turkey': { score: 6, category: 'lean_protein' },
  'ground chicken': { score: 6, category: 'lean_protein' },
  'ground beef': { score: 2, category: 'lean_protein' },
  'lean ground beef': { score: 5, category: 'lean_protein' },
  'pork chop': { score: 3, category: 'lean_protein' },
  'ribeye steak': { score: 2, category: 'lean_protein' },
  'sirloin steak': { score: 4, category: 'lean_protein' },
  'flank steak': { score: 5, category: 'lean_protein' },
  'tilapia': { score: 7, category: 'lean_protein' },
  'halibut': { score: 9, category: 'lean_protein' },
  'mahi mahi': { score: 8, category: 'lean_protein' },
  'mackerel': { score: 9, category: 'lean_protein' },
  'crab': { score: 7, category: 'lean_protein' },
  'lobster': { score: 6, category: 'lean_protein' },
  'mussel': { score: 8, category: 'lean_protein' },
  'scallop': { score: 8, category: 'lean_protein' },
  'prosciutto': { score: -4, category: 'processed' },
  'pancetta': { score: -5, category: 'processed' },
  'meatball': { score: -2, category: 'processed' },
  'veggie burger': { score: 5, category: 'lean_protein' },
  'impossible burger': { score: 3, category: 'processed' },
  'beyond burger': { score: 3, category: 'processed' },
  // Beverages
  'water': { score: 10, category: 'vegetable_fruit' },
  'sparkling water': { score: 9, category: 'vegetable_fruit' },
  'la croix': { score: 9, category: 'vegetable_fruit' },
  'unsweetened tea': { score: 7, category: 'vegetable_fruit' },
  'green tea': { score: 8, category: 'vegetable_fruit' },
  'black coffee': { score: 6, category: 'vegetable_fruit' },
  'coconut water': { score: 4, category: 'vegetable_fruit' },
  'kombucha': { score: 4, category: 'vegetable_fruit' },
  'protein shake': { score: 2, category: 'lean_protein' },
  'milkshake': { score: -7, category: 'fast_food_sugary' },
  'smoothie': { score: 4, category: 'vegetable_fruit' },
  'juice box': { score: -5, category: 'fast_food_sugary' },
  'fruit punch': { score: -7, category: 'fast_food_sugary' },
  // Oils / fats
  'olive oil': { score: 5, category: 'processed' },
  'extra virgin olive oil': { score: 6, category: 'processed' },
  'avocado oil': { score: 5, category: 'processed' },
  'canola oil': { score: 0, category: 'processed' },
  'vegetable oil': { score: -1, category: 'processed' },
  'coconut oil': { score: 1, category: 'processed' },
  'sesame oil': { score: 3, category: 'processed' },
  // Dressings
  'vinaigrette': { score: 1, category: 'processed' },
  'italian dressing': { score: 0, category: 'processed' },
  'caesar dressing': { score: -3, category: 'processed' },
  'thousand island': { score: -3, category: 'processed' },
  'blue cheese dressing': { score: -3, category: 'processed' },
  'balsamic vinegar': { score: 3, category: 'processed' },
};

function normalize(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, ' ')
    .replace(/s$/, '');
}

// Look up a score by name. Tries exact normalized match, then a raw lowercase
// match, then whole-word substring of any table key.
export function lookupFoodScore(name: string): ScoreEntry | null {
  const n = normalize(name);
  if (FOOD_SCORE_TABLE[n]) return FOOD_SCORE_TABLE[n];

  const raw = name.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, ' ');
  if (FOOD_SCORE_TABLE[raw]) return FOOD_SCORE_TABLE[raw];

  for (const key of Object.keys(FOOD_SCORE_TABLE)) {
    if (key.length < 4) continue;
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp(`\\b${escaped}\\b`);
    if (re.test(raw)) return FOOD_SCORE_TABLE[key];
  }

  return null;
}
